---
title: "p8105_hw2_xk2163"
author: "Kang"
date: "2024-10-01"
output: github_document
---

```{r, message=FALSE}
library(tidyverse)
library(readxl)
```


# Problem 1

line, station, name, station latitude / longitude, routes served, entry, vending, entrance type, and ADA compliance

entry variable from character (YES vs NO) to a logical variable
case_match

explain briefly what variables ::skim

dimension

this data tidy?

```{r}
data_transit_df = 
  read_csv(
    "NYC_Transit_Subway_Entrance_And_Exit_Data.csv",
    col_types = cols(Route8 = "c", Route9 = "c", Route10 = "c", Route11 = "c")) %>% 
  janitor::clean_names() %>% 
  select(
    line, station_name, station_latitude, station_longitude, 
    starts_with("route"), entry, exit_only, vending, entrance_type, 
    ada) %>% 
  mutate(entry = ifelse(entry == "YES", TRUE, FALSE))
```

```{r}
skimr::skim(data_transit_df)
```

# Problem 2

```{r}
sheet_names = 
  excel_sheets("202409 Trash Wheel Collection Data.xlsx")

data2_df =bind_rows(read_excel("202409 Trash Wheel Collection Data.xlsx",
                      skip = 1,sheet = sheet_names[1],n_max = 651) %>% 
         mutate(name_tag = sheet_names[1],
                Year = as.integer(Year)),
      read_excel("202409 Trash Wheel Collection Data.xlsx",
                      skip = 1,sheet = sheet_names[2],n_max = 118) %>% 
         mutate(name_tag = sheet_names[2]),
      read_excel("202409 Trash Wheel Collection Data.xlsx",
                      skip = 1,sheet = sheet_names[4],n_max = 263) %>% 
         mutate(name_tag = sheet_names[4]))%>% 
  janitor::clean_names() %>% 
  select(-dumpster) %>%
  relocate(name_tag) %>% 
  mutate(sports_balls = as.integer(sports_balls))


# weight tons of Professor Trash Wheel
data2_df %>% 
  filter(name_tag == "Professor Trash Wheel") %>% 
  summarize(sum(weight_tons))

#the total number of cigarette butts collected by Gwynnda in June of 2022

data2_df %>% 
  filter(name_tag == "Professor Trash Wheel" &
        month == "June" & year == 2022) %>% 
  summarize(sum(cigarette_butts))
```

# Problem 3

```{r}
data_3_1 = 
  read_csv("gbb_datasets/bakers.csv") %>% 
  janitor::clean_names() %>% 
  mutate(baker = baker_name) %>% 
  select(-baker_name) %>% 
  separate(baker,into = c("baker","last_name"), sep = " ")

data_3_2 = read_csv("gbb_datasets/bakes.csv") %>% 
  janitor::clean_names()

data_3_3 = read_csv("gbb_datasets/results.csv",skip = 2) %>% 
  janitor::clean_names()

data_3_4 = read_csv("gbb_datasets/viewers.csv") %>% 
  pivot_longer(
    cols = starts_with("Series"),
    names_to = "tag",
    values_to = "viewers") %>% 
  separate(tag, into = c("name", "series"), sep = " ") %>% 
  select(-name) %>% 
  janitor::clean_names() %>% 
  mutate(series = as.double(series))

# check for completeness and correctness

anti_join(data_3_1,data_3_2, by = c("baker","series"))

anti_join(data_3_1,data_3_3, by = c("baker","series"))

anti_join(data_3_2,data_3_3, by = c("baker","series","episode"))

data3_df = 
  data_3_1 %>%
  full_join(data_3_2, by = c("baker","series")) %>% 
  full_join(data_3_3, by = c("baker","series","episode"))

# Clear table

clear_table = 
  data3_df %>% 
  filter(result == "STAR BAKER" | result == "WINNER") %>% 
  filter(series %in% c(5:10))


#Import, clean, tidy, and organize the viewership data in viewers.csv. Show the first 10 rows of this dataset. What was the average viewership in Season 1? In Season 5?

data_3_4 %>% 
  filter(series == 1) %>% 
  summarize(mean(viewers,na.rm = TRUE))

data_3_4 %>% 
  filter(series == 5) %>% 
  summarize(mean(viewers,na.rm = TRUE))
```

